### ISSUE TITLE
нужны примеры использования

### ISSUE THREAD

**Issue by dmitry4m** [WhiteApfel/tochka_api#1]
а можно для начинающих сделать пару примеров или перечень имеющихся функций с параметрами их использования?

например, мне нужно генерировать динамический QR код на оплату, а потом отследить факт оплаты по нему.
было бы здорово получить пример кода. 
код для регистрации мерчанта в README немного сбивает, ведь мерчант уже зарегистрирован в личном кабинете, это разовая операция.

**Comment by WhiteApfel** [comment]
Есть документация API: https://enter.tochka.com/doc/v2/redoc/section/Opisanie-metodov

Методы библиотеки в целом соответствуют методам API можно искать поиском по URI методов в коде

**Comment by WhiteApfel** [comment]
Код старался писать достаточно понятно, чтобы его можно было безболезненно смотреть в качестве документации библиотеки
